apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.container.name }}-deployment"
  labels:
    app: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        project: {{ .Values.container.name }}
    spec:
      containers:
        - name: "{{ .Values.container.name }}-app"
          image: "{{ .Values.container.image }}:{{ .Values.container.tag }}"
          ports:
            - containerPort: {{ .Values.container.port }}
          