apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.container.name }}-service"
  labels:
    env: dev
  namespace: default
spec:
  selector:
    project: {{ .Values.container.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
  type: NodePort