apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eksdemo
  template:
    metadata:
      labels:
        app: eksdemo
    spec:
      containers:
        - name: todo
          image: 025389115636.dkr.ecr.us-east-1.amazonaws.com/dev/demo3:latest
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: eksdemo
  ports:
    - nodePort: 31479 #external traffic
      port: 7577 #port of this service. Cluster members talk via this port
      targetPort: 8002 #where container is actually running