apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Demo-4
  region: us-east-1

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.micro
    desiredCapacity: 1
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t3.micro
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true